package day32_Constructors.day32_Constructors.day42_ExceptionsContinue;

public class ThrowsKeyword2 {
    public static void main(String[] args) throws ArithmeticException {

        System.out.println("Test started");

        System.out.println(8/0);

        System.out.println("Test completed");



    }

}
